### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by drosenberg-gh** [neil-morrison44/homebridge-am43-blinds-bluez#1]
I'm trying to install and keep getting the following error message:

npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 243

Any help would be greatly appreciated

**Comment by neil-morrison44** [comment]
@drosenberg-gh thanks for giving it a shot - it’s probably the next few lines of the error that’d say what’s going wrong - the `WARN` bits wouldn’t cause it to not install

**Comment by drosenberg-gh** [comment]
My bad, here is the rest of the error 

npm ERR! code 243
npm ERR! git dep preparation failed
npm ERR! command /usr/bin/node /usr/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/home/username/.npm --prefer-offline=false --prefer-online=true --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm ERR! code EACCES
npm ERR! npm ERR! syscall symlink
npm ERR! npm ERR! path ../../../home/username/.npm/_cacache/tmp/git-clone3quyUI
npm ERR! npm ERR! dest /usr/lib/node_modules/node-ble
npm ERR! npm ERR! errno -13
npm ERR! npm ERR! Error: EACCES: permission denied, symlink '../../../home/username/.npm/_cacache/tmp/git-clone3quyUI' -> '/usr/lib/node_modules/node-ble'
npm ERR! npm ERR!  [Error: EACCES: permission denied, symlink '../../../home/username/.npm/_cacache/tmp/git-clone3quyUI' -> '/usr/lib/node_modules/node-ble'] {
npm ERR! npm ERR!   errno: -13,
npm ERR! npm ERR!   code: 'EACCES',
npm ERR! npm ERR!   syscall: 'symlink',
npm ERR! npm ERR!   path: '../../../home/username/.npm/_cacache/tmp/git-clone3quyUI',
npm ERR! npm ERR!   dest: '/usr/lib/node_modules/node-ble'
npm ERR! npm ERR! }
npm ERR! npm ERR! 
npm ERR! npm ERR! The operation was rejected by your operating system.
npm ERR! npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! npm ERR! 
npm ERR! npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! npm ERR! permissions of the file and its containing directories, or try running
npm ERR! npm ERR! the command again as root/Administrator.
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in:

**Comment by neil-morrison44** [comment]
Ah right, yeah - I’ve seen that, was hoping it was something weird on my homebridge instance. I’ll have a look into solving it

If you want a workaround you can install it manually using
`npm install -g homebridge-plugin-am43-blinds-bluez` as another user

**Comment by gielk** [comment]
I think you mean `npm install -g homebridge-am43-blinds-bluez`

because `Not Found - GET https://registry.npmjs.org/homebridge-plugin-am43-blinds-bluez - Not found`
